jQuery.sap.declare("sap.umc.mobile.CONSTANTS");

sap.umc.mobile.CONSTANTS = jQuery.extend(sap.umc.mobile.base.CONSTANTS, {
	ODATA_SERVICE_NAMESPACE: "/sap/opu/odata/sap/",
	ODATA_SERVICE_NAMESPACE_USERMANAGEMENT: "/sap/opu/odata/IWBEP/",
	ODATA_SERVICE_CRM: "CRM_UTILITIES_UMC",
	ODATA_SERVICE_ERP: "ERP_UTILITIES_UMC",
	ODATA_SERVICE_GEO: "VBI_GEOCODER_SRV",
	ODATA_SERVICE_VBI: "VBI_APPL_DEF_SRV",
	ODATA_SERVICE_CRM_URM: "CRM_UTILITIES_UMC_URM",
	ODATA_SERVICE_USERMANAGEMENT: "USERMANAGEMENT/",
	STATE_CHANGED: "changed",
	STATE_UNCHANGED: "unchanged",

	CREATE_USER: "0",
	RESET_PASSWORD: "1",
	CHANGE_PASSWORD: "2",
	CREATEUSER_WITHPASSWORD: "3",

	"CRM_UTILITIES_UMC": {
		METADATA_NAME: "CRM_UTILITIES_UMC_METADATA"
	},
	"ERP_UTILITIES_UMC": {
		METADATA_NAME: "CRM_UTILITIES_UMC_METADATA"
	},
	BUDGETBILLINGPROCEDURE: {
		BUDGETBILLING_STATISTICAL: "1",
		BUDGETBILLING_PARTIAL: "2",
		PAYMENTPLAN: "3"
	},
	COMPONENTS: {
		HOME: "HomeComponent",
		SERVICES: "ServicesComponent",
		CHANGE_SERVICE: "ChangeServiceComponent",
		INVOICE: "InvoiceComponent",
		MESSAGE_CENTER: "MessageCenterComponent",
		INTERACTION_RECORD: "InteractionRecordComponent",
		CONTRACT: "ContractComponent",
		USER_PROFILE: "UserProfileComponent",
		Outage: "OutageComponent"
	},
	MESSAGE_TYPE: {
		ALERT: "AL",
		SERVICE_NOTIFICATION: "NT",
		OUTAGE: "OT",
		INTERACTION_RECORD: "IR"
	},
	ALERT_SEVERITY: {
		ERROR: "E",
		WARNING: "W",
		SUCCESS: "S",
		INFO: "I"
	},
	ALERT_TYPE: {
		INVOICE: "1"
	},
	OUTAGES: {
		APP_ID: "ZUMC",
		PROVIDER: "HERE",
		BROADCAST: "7"
	},
	COMMUNICATION_PREFERENCES: {
		EMAIL: "MAIL",
		MAIL: "STND",
		LETTER: "LET",        
		NOT_SET: "NONE",
		MOBILE: "SMS",
		GC_CAT_BILLING: "UMCB",
		GC_CAT_BILL_NOTIFICATION: "UMC1",
		GC_CAT_OUTAGE: "UMC2"
	},
	COMMUNICATION_PERMISSIONS: {
		EMAIL: "INT",
		MOBILE: "PAG",
		NOT_SET: "NONE",
		LETTER: "LET",
		GIVEN: "001",
		REJECTED: "002"
	},
	PAYMENT_METHODS: {
		PAYMENT_BANK: "A",
		PAYMENT_CARD: "K",
		BANK: "bank",
		CARD: "card"
	},
	CHANGE_SERVICE_CONTEXT: {
		START_SERVICE: "START_SRV",
		TRANSFER_SERVICE: "TANSFER_SRV",
		END_SERVICE: "END_SRV",
		CHANGE_PRODUCT: "CHANGE_PRD"
	},
	DIVISIONS: {
		ELECTRICITY: "01",
		GAS: "02",
		WATER: "03"
	},
	REQUESTED_SERVICE_TYPE: {
		PENDING_SERVICE: "PendingService",
		QUOTATION: "Quotation"
	},
	TIMEPERIOD: {
		MONTH: "MON",
		DAY: "DAY",
		HOUR: "60"
	},
	CONSUMPTION_TYPE: {
		HISTORICAL: "H",
		FORECAST: "F"
	},
	SMARTMETER_DISPLAY_TYPE: {
		UNIT: "unit",
		CURRENCY: "currency"
	},
	PAYMENT_STATUS: {
		OPEN: "1",
		RELEASED_BY_CUSTOMER: "2",
		AUTOMATIC_COLLECTION: "3",
		CLEARED: "9"
	}
});
